### ISSUE TITLE
Naming conflict with official NGX Logger

### ISSUE THREAD

**Issue by PeterWippermann** [A1rPun/ngx-logger#1]
I found this project when searching for [the "official" NGX Logger](https://github.com/dbfannin/ngx-logger). Is the naming conflict intended? If not, would you please rename your project, so the URL does no longer contain "ngx-logger"? That would be great to prevent any misunderstandings for users.

**Comment by A1rPun** [comment]
At first I thought you made a joke but I guess I handle this seriously.
Can you please look at the time my repository was created, Jun 2 2017, then look at the time the "official" repository was created, Dec 8 2017.
Furthermore I hope they don't claim to be an official repository because none of the contributers is from an angular team.
I won't rename my repo for a couple of reasons:
- That's the naming convention for angularlike components
- At the time there were no good loggers for angular2
- Anyone can easily distinguish my unofficial logger against some well written implementation ;)

**Comment by PeterWippermann** [comment]
Hi @A1rPun ,
as a user I'm not aware of any Angular naming convention. If that's indeed the convention it obviously doesn't scale very well as naming conflicts are likely. From the repo's homepage I also don't see how old both projects are: Sorry, if your project was the first one.

Can you please explain how those two projects are easy to distinguish from each other?

**Comment by A1rPun** [comment]
Hey @PeterWippermann, you are right about the fact that it can lead to naming conflicts as we are currently experiencing. You can distinguish projects based on creator, intent and stars (meaning the project will be supported by more people).

I have used my repo in production code and it does what it need to do. I can tell the repo you linked also does the logging well (almost identical) but has some other options as well. Just weight out the pro's and con's and work with the tools you need.
